### PR TITLE
ka - a new Last Day Date entry (setting the end date of a game) + gameInProgress() function telling whether the game is ongoing

### LINKED ISSUE #41: FEATURE: As an admin, I have access to a "Last Day Date" entry for every commons. (Break from #10)
# User Story
* As an admin
* I can see and control when the game ends for particular commons
* So I know which games have finished and can be deleted

# Discussion

There is currently a start date associated with each commons.  In this issue we are just adding an end date 
for the game. 

## Acceptance Criteria

- [x] Add lastday date. (this is more clear than end date, since it indicates that the game ends at 11:59:59 on that day).  Needs to be added to entity in backend, POST and PUT endpoints in backend, form in frontend, and adjusted on Create and Update pages.

### LINKED ISSUE #44: FEATURE: As an admin, I can see if a game is ongoing (current date is within the lifespan of the game) (Brake from #10)
# User Story
* As an admin
* I can know whether a game is live or not
* So that the server doesn't accumulate database records that are useless and eventually crash

# Discussion

There is currently a start date associated with each commons.  In this issue we are just adding an end date 
for the game. 

## Acceptance Criteria

- [x] Add a function to the Commons entity (and tests for it) called gameInProgress() that returns true if today's date is >= start date, and <= end date.  This could be it's own PR, with tests.  Note that mocking "today's date" is possible; tricky, but possible.

### PR DESCRIPTION
**Pull request by kirrarista**
Adds a Last Day Date entry visible and changeable by admin users. Both back and frontend are done and work exactly the same way as Starting Date. 
Adds a function checking whether a game is in progress. (will be helpful for future derivations from #10)

Screenshot 2023-08-24 at 10 33 40 PM
Screenshot 2023-08-24 at 10 33 50 PM

Deployed for testing: https://proj-happycows-kirrarista.dokku-05.cs.ucsb.edu/

Closes #41
Closes #44

### CODE REVIEW

**Review by jczhou02 — CHANGES_REQUESTED** [review]
It looks like your lacking testing for empty header, cells, or fields. This can be seen in the mutation report which I pasted for you right here:

[Survived] StringLiteral
src/main/components/Commons/CommonsTable.js:69:20
-               Header:'Last Day Date',
+               Header:"",

[Survived] ArrowFunction
src/main/components/Commons/CommonsTable.js:70:23
-               accessor: row => String(row.commons.lastdayDate).slice(0,10),
+               accessor: () => undefined,

[Survived] MethodExpression
src/main/components/Commons/CommonsTable.js:70:30
-               accessor: row => String(row.commons.lastdayDate).slice(0,10),
+               accessor: row => String(row.commons.lastdayDate),

[Survived] StringLiteral
src/main/components/Commons/CommonsTable.js:71:17
-               id: 'commons.lastdayDate'
+               id: ""

**Review by jczhou02 — APPROVED** [review]
Looks good to me! Maybe include some screenshots?

**Review by rockygao2020 — APPROVED** [review]
Tested Dokku to confirm end date works find. looked into files change to confirm function also makes sense.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
